FROM debian:stable

RUN apt update && apt install -y ruby ruby-dev libffi-dev gcc make virtualenv git python3-pip

RUN gem install fpm
RUN pip3 install virtualenv-tools3 wheel

RUN echo '#!/bin/bash -ex\n/usr/bin/virtualenv --python=python3 $@' >/usr/local/bin/virtualenv
RUN chmod a+x /usr/local/bin/virtualenv

ADD . /code
WORKDIR /code

ENTRYPOINT ["/usr/local/bin/fpm"]
