FROM debian:stable

RUN apt update && apt upgrade -y
RUN apt install -y apache2 libapache2-mod-wsgi-py3 python3

ADD *.deb /packages/
RUN apt install -fy /packages/*.deb

CMD apache2ctl start && tail -f /var/log/apache2/*.log
